### ISSUE TITLE
Getting error while training

### ISSUE THREAD

**Issue by quicktwit** [mabaorui/OnSurfacePrior#2]
Hi
I would like to thank the author for this great research.
I am trying this repository on my point cloud data (in .ply format).

I am getting error while training:
```
Traceback (most recent call last):
  File “onSurPrior.py”, line 747, in <module>
    index_fine = np.random.choice(SP_NUM//10, POINT_NUM, replace = True)
  File “mtrand.pyx”, line 902, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken 
```
When I check SP_NUM then it showing 0
Here is the header of my point cloud file:
```
ply
format binary_little_endian 1.0
element vertex 2524937
property float x
property float y
property float z
property float nx
property float ny
property float nz
property uchar red
property uchar green
property uchar blue
property uchar views
end_header
```

Can you help me why I am getting this error?
Thank you in advance. I really appreciate for it.

My PC env:
Ubuntu 20.04
GPU: GeForce RTX3090 24GB

**Comment by mabaorui** [comment]
Hi,
This problem is the result of your points cloud is too large. Similar issues and corresponding codes are available at the following links.
https://github.com/mabaorui/NeuralPull-Pytorch/issues/1#issue-1276022186
https://github.com/mabaorui/OnSurfacePrior/blob/d53bf3a7bc88837e2974ddc1fd0700ecc2641ade/onSurPrior.py#L408

**Comment by quicktwit** [comment]
Hi @mabaorui 
Thank you so much for the response. 
It worked after increasing the point cloud in line 408.
And I got an OOM (Out of Memory) Error.
So I think you advised to run on CPU.
I tried to run it on the CPU and it is training.
