### ISSUE TITLE
Loss showing NaN

### ISSUE THREAD

**Issue by quicktwit** [mabaorui/OnSurfacePrior#3]
After fixing this issue:
https://github.com/mabaorui/OnSurfacePrior/issues/2
I got nan on epoch:
`epoch: 0 epoch loss: nan loss_sdf: nan move loss: nan`
I even reduced the learning rate but didn't help.
What am I missing?
Thank you in advance @mabaorui.

**Comment by mabaorui** [comment]
Hi,
You can try downsampling the point cloud to a few tens of thousands of points and run it on the GPU to see if there are still problems.

**Comment by quicktwit** [comment]
Hi @mabaorui 
Thank you for your response.
After downsampling, I could get the loss. Thank you again!! I will close the issue.
